"""The contract every code-intelligence backend implements. Methods return plain JSON-safe dicts; `precision` says how much to trust a name match."""
from typing import Protocol

PRECISIONS = ('lexical', 'syntactic', 'semantic')  # lexical: word/name match; syntactic: parsed structure, names unresolved; semantic: type-resolved

class SymbolProvider(Protocol):
    name: str

    def definitions(self, name: str, kind: str | None = None, limit: int = 20) -> dict: ...
    def references(self, name: str, limit: int = 40) -> dict: ...
    def implementations(self, name: str, limit: int = 40) -> dict: ...
    def callers(self, name: str, limit: int = 40) -> dict: ...
    def callees(self, name: str, limit: int = 40, path: str | None = None) -> dict: ...
    def diagnostics(self, paths: list[str] | None = None, limit: int = 60) -> dict: ...
    def symbol_context(self, name: str, budget: int = 6000, path: str | None = None) -> dict: ...
    def outline(self, path: str) -> dict: ...

def answer(provider, precision, **data):
    assert precision in PRECISIONS
    return {'provider': provider, 'precision': precision, **data}
